# AutoHound © 2026 Gordon Prescott

"""
ATT&CK Navigator layer generator.

Generates JSON layer files compatible with MITRE ATT&CK Navigator
for visualization of techniques used in discovered attack paths.
"""

import json
import logging
from pathlib import Path

from autohound.models import AttackPath

logger = logging.getLogger(__name__)


class AttackNavigatorGenerator:
    """Generate ATT&CK Navigator layer files."""

    LAYER_TEMPLATE = {
        "name": "AutoHound Attack Paths",
        "versions": {
            "attack": "14",
            "navigator": "4.9",
            "layer": "4.5"
        },
        "domain": "enterprise-attack",
        "description": "Attack techniques identified by AutoHound analysis",
        "filters": {
            "platforms": ["Windows"]
        },
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": True,
            "showName": True,
            "showAggregateScores": False,
            "countUnscored": False
        },
        "hideDisabled": False,
        "techniques": [],
        "gradient": {
            "colors": [
                "#ff6666",
                "#ffe766",
                "#8ec843"
            ],
            "minValue": 0,
            "maxValue": 100
        },
        "legendItems": [],
        "metadata": [],
        "links": [],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossLevels": True,
        "selectSubtechniquesWithParent": False
    }

    def __init__(self, attack_paths: list[AttackPath]):
        """
        Initialize navigator generator.

        Args:
            attack_paths: Attack paths to visualize
        """
        self.attack_paths = attack_paths

    def generate(self, output_path: Path) -> None:
        """
        Generate ATT&CK Navigator layer JSON file.

        Args:
            output_path: File path for the layer file
        """
        logger.info(f"Generating ATT&CK Navigator layer: {output_path}")

        # Collect all techniques from paths
        techniques = self._collect_techniques()

        # Build layer
        layer = self.LAYER_TEMPLATE.copy()
        layer["techniques"] = techniques
        layer["metadata"] = [
            {
                "name": "Generated by",
                "value": "AutoHound v0.1"
            },
            {
                "name": "Total Paths",
                "value": str(len(self.attack_paths))
            }
        ]

        # Write to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(layer, f, indent=2)

        logger.info(f"ATT&CK Navigator layer generated: {output_path}")

    def _collect_techniques(self) -> list[dict]:
        """Collect and aggregate techniques from all paths."""
        # Track techniques and their scores
        technique_data: dict[str, dict] = {}

        for path in self.attack_paths:
            for step in path.steps:
                if not step.attack_technique_id:
                    continue

                tech_id = step.attack_technique_id

                if tech_id not in technique_data:
                    technique_data[tech_id] = {
                        "techniqueID": tech_id,
                        "tactic": step.attack_tactic or "unknown",
                        "score": path.overall_score,
                        "color": self._score_to_color(path.overall_score),
                        "comment": f"Used in path: {path.name}",
                        "enabled": True,
                        "metadata": [],
                        "links": [],
                        "showSubtechniques": False
                    }
                else:
                    # Aggregate: take highest score
                    if path.overall_score > technique_data[tech_id]["score"]:
                        technique_data[tech_id]["score"] = path.overall_score
                        technique_data[tech_id]["color"] = self._score_to_color(path.overall_score)

                    # Append to comment
                    technique_data[tech_id]["comment"] += f"\n- {path.name}"

        return list(technique_data.values())

    def _score_to_color(self, score: float) -> str:
        """Map overall score to color."""
        if score >= 80:
            return "#ff6666"  # Red - critical
        elif score >= 60:
            return "#ffa500"  # Orange - high
        elif score >= 40:
            return "#ffe766"  # Yellow - medium
        else:
            return "#8ec843"  # Green - low
